<template>
<div style="position: relative; width: 100%; height: 100%;">
  <div style="width: 65%; height: 80%; top: 10%; left: 5%; position: absolute;">
    <div
      :class="['game-board', 'board-background-' + data.boardSettings.background]"
      ref="board"
      panels="control">
    </div>
    Your Color: {{userColor == -1 ? "Black" : "White"}}
  </div>
  <div style="left: 75%; top: 10%; height: 80%; width: 25%; position: absolute;">
    <div>
      <h2>
        {{data.title}}
      </h2>
    </div>
    <div v-html="data.text"></div>
    <div>
      <button @click="board.editor.click(0, 0, false)">Pass</button>
    </div>
  </div>
</div>
</template>

<script>
import AI from '../classes/AI';

export default {
  props: ['data', 'config'],
  data () {
    return {
      userColor: -1,
      board: null,
      ai: null
    }
  },
  computed: {
  },
  methods: {
    setupBoard() {
      this.$refs.board.innerHTML = this.data.boardSettings.sgf;

      this.board = besogo.create(this.$refs.board, {
        panels: [],
        tool: 'playWithoutUndo',
        nowheel: true,
        nokeys: true,
        customstones: this.data.boardSettings.customstones
      })

      if (this.userColor == 1) {
        this.config.genMove(this.board);
      }

      this.ai = new AI(this.config.aiSettings);

      this.board.editor.addListener((data) => {
        if (
          data.treeChange &&
          this.board.editor.getCurrent().move.color == this.userColor
        ) {

          // Prevent moves
          this.board.editor.setTool('none');

          this.ai.genMove(this.board).then((aiMove) => {
            // Play the move generated by the AI
            this.board.editor.playMove(aiMove.x, aiMove.y);
          }).finally(() => {
            // Enable playing again
            this.board.editor.setTool('playWithoutUndo');
          });
        }
      });
    }
  },
  mounted () {
    if (this.data.boardSettings.userColor) {
      this.userColor = this.data.boardSettings.userColor;
    }

    this.$nextTick(() => {
      this.setupBoard()
    })
  }
}
</script>

<style lang="scss">
  .game-board {
    width: 100% !important;
    height: 100% !important;
  }

  .game-board.besogo-container {
    background: inherit;
  }

  .board-background-water {
    .besogo-svg-board {
      fill: #6688cd;
    }
  }
</style>
